### ISSUE TITLE
npm run build  Error occurred

### ISSUE THREAD

**Issue by costs** [NeutroniumCore/neutronium-vue#1]
i Download the original template ,Generating an error;
No editing

ERR:
 Asset     Size  Chunks             Chunk Names
build.js  1.51 kB       0  [emitted]  main

ERROR in ./src/App.vue
Module build failed: TypeError: loader.charAt is not a function
    at ensureBang (D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:180:16)
    at getLoaderString (D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:145:18)
    at getRequireString (D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:80:7)
    at getRequire (D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:71:7)
    at D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:205:11
    at Array.forEach (native)
    at Object.module.exports (D:\cef\DrunkGame\DrunkGame.View\View\view3\node_modules\vue-loader\lib\loader.js:198:18)
 @ ./src/entry.js 2:0-28

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! view3@ build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the view3@ build script 'cross-env NODE_ENV=production webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the view3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs view3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls view3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by David-Desmaisons** [comment]
@costs Thanks for pinting ou this one. I am working on it.

**Comment by David-Desmaisons** [comment]
Hello @costs , I just updated neutronium-vue to version 2.0 that includes correction for this issue and update to current webpack version.
