### ISSUE TITLE
 Still exist npm run build Error occurred

### ISSUE THREAD

**Issue by costs** [NeutroniumCore/neutronium-vue#2]
Sorry that I was still unsuccessful; is the system environment?

debug.log
D:\LOC\NeutoniumDemo-master\NeutoniumDemo\View\page4>npm run build
> page4@ build D:\LOC\NeutoniumDemo-master\NeutoniumDemo\View\page4
> cross-env NODE_ENV=production webpack --progress --hide-modules

D:\LOC\NeutoniumDemo-master\NeutoniumDemo\View\page4\webpack.config.js:113
webpackOptions.module.rules = webpackOptions.module.rules.concat(utils.styleLoaders(styleOption}))
                                                                                    ^^^^^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (D:\LOC\NeutoniumDemo-master\NeutoniumDemo\View\page4\node_modules\webpack\bin\convert-argv.js:96:18)
    at D:\LOC\NeutoniumDemo-master\NeutoniumDemo\View\page4\node_modules\webpack\bin\convert-argv.js:109:17

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! page4@ build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the page4@ build script 'cross-env NODE_ENV=production webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the page4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs page4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls page4
npm ERR! There is likely additional logging output above.

**Comment by David-Desmaisons** [comment]
Hello @costs . version 2.2.1 corrects this issue. Please confirm that everything is fine now.

**Comment by costs** [comment]
Hello @David-Desmaisons     success，   Thank you.

**Comment by David-Desmaisons** [comment]
Thanks for the feedback, I am closing the issue.
