### ISSUE TITLE
npm install vue-materail removes 637 packages

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/neutronium-vue#3]
When using the Neutronium-Vue project template...

```
[...]\View\Main>npm install vue-material
+ vue-material@0.8.1
removed 637 packages and updated 1 package in 35.528s

```
I've used npm before, this is not what I expected (seriously violates principle of least astonishment). I'm assuming this has something to do with how the template is packaged. Please provide some guidance on the proper way to include extra node packages without destroying everything. Thanks!

**Comment by fizxmike** [comment]
I think this happened because npm was rolling back "failed" install. Turns out I do not have python installed which is required for npm to (at least) install node-sass.

Trying running npm install windows-build-tools first!

**Comment by fizxmike** [comment]
installing this first does the trick: https://www.npmjs.com/package/windows-build-tools maybe add this to documentation (although it may be obvious to others... it wasn't for me).

**Comment by David-Desmaisons** [comment]
@fizxmike thanks for reporting issue and updating status. I don't think thougth that this issue is related to neutronium itself. From what I understand it seems to be related on how to install node-sass (and resolves its Python dependency).

**Comment by fizxmike** [comment]
@David-Desmaisons I agree.
