### ISSUE TITLE
NaN not parsed properly

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/neutronium-vue#4]
https://github.com/NeutroniumCore/neutronium-vue/blob/86dde3ac9fade8dc7db0fbaeab1679391854ee73/template/src/main.js#L16

When saving my ViewModel I have some (expected) NaNs in my data/vm.cjson

When running in webpack dev mode, the line linked above throws an error. I had to do a string replace like so to get it to work:

`const vm = updateVm(CircularJson.parse(rawVm.replace(/\bNaN\b/g, '"NaN"')));
`
However, I believe there is a possibility of Infinity and -Infinity too... so my hack doesn't completely solve problems like this.

**Comment by David-Desmaisons** [comment]
Could you please share the cjson file so I can investigate?

**Comment by fizxmike** [comment]
Here ya go (remove .txt extension of course)! Like I said, technically both NaN and Infinity (and -Infinity) are possible in such json dumps... you could decide to catch this at dump time.

[vm.cjson.txt](https://github.com/NeutroniumCore/neutronium-vue/files/1557701/vm.cjson.txt)

**Comment by David-Desmaisons** [comment]
Thanks! I already corrected a bug in the generation of cjson in the upcoming version.
I will take chance and include this correction too.

**Comment by David-Desmaisons** [comment]
Closed in version 5.1.0
